package vtvibe

import (
	"context"
	"io"
	"os"
	"path"
	"strings"

	"github.com/unxed/f4/vfs"
)

// AIVFS exposes a Session as an ordinary file system. That is the whole idea
// of vtvibe: the context of a model is a folder, so F5, F8, F3 and F4 keep
// the meaning they have had for twenty years and no new UI is invented.
//
// Every AIVFS instance created from the same Session shares its state, which
// is what makes "copy from the left panel into the dialog on the right" work.
type AIVFS struct {
	s   *Session
	cwd string
}

// NewVFS mounts a session as a drive.
func NewVFS(s *Session) *AIVFS { return &AIVFS{s: s, cwd: "/"} }

// Session returns the dialog behind this mount.
func (v *AIVFS) Session() *Session { return v.s }

// SessionKey lets f4 recognize two mounts of the same dialog, so copying a
// file onto itself is refused the way it is on any other file system.
func (v *AIVFS) SessionKey() any { return v.s }

func (v *AIVFS) IsAtRoot() bool  { return v.cwd == "/" }
func (v *AIVFS) GetPath() string { return v.cwd }
func (v *AIVFS) IsAbs(p string) bool {
	return strings.HasPrefix(p, "/") || strings.HasPrefix(p, "ai://")
}

func (v *AIVFS) SetPath(p string) error {
	target := v.normalize(p)
	if n, ok := v.s.tree.stat(target); !ok || !n.isDir {
		return os.ErrNotExist
	}
	v.cwd = target
	return nil
}

// GetTitle and PanelTitle keep the panel header reading ai://ctx rather than
// a bare /ctx that looks like a local folder.
func (v *AIVFS) GetTitle() string { return "ai" }

func (v *AIVFS) PanelTitle(p string) string {
	return "ai://" + strings.TrimPrefix(CleanPath(p), "/")
}

func (v *AIVFS) normalize(p string) string {
	p = strings.TrimPrefix(p, "ai://")
	if p != "" && !strings.HasPrefix(p, "/") && !strings.HasPrefix(p, "\\") {
		p = path.Join(v.cwd, p)
	}
	return CleanPath(p)
}

func (v *AIVFS) ReadDir(ctx context.Context, p string, onChunk func([]vfs.VFSItem)) error {
	v.s.refresh()
	target := v.normalize(p)
	n, ok := v.s.tree.stat(target)
	if !ok || !n.isDir {
		return os.ErrNotExist
	}
	if onChunk == nil {
		return nil
	}
	children := v.s.tree.list(target)
	items := make([]vfs.VFSItem, 0, len(children))
	for _, c := range children {
		items = append(items, toItem(c))
	}
	if len(items) > 0 {
		onChunk(items)
	}
	return ctx.Err()
}

func (v *AIVFS) Stat(ctx context.Context, p string) (vfs.VFSItem, error) {
	v.s.refresh()
	target := v.normalize(p)
	n, ok := v.s.tree.stat(target)
	if !ok {
		if altNode, altOk := v.s.tree.stat(path.Join(ctxDir, path.Base(target))); altOk {
			n, ok = altNode, true
		} else if altNode, altOk := v.s.tree.stat(path.Join(outDir, path.Base(target))); altOk {
			n, ok = altNode, true
		}
	}
	if !ok {
		return vfs.VFSItem{}, os.ErrNotExist
	}
	item := toItem(n)
	if target == "/" {
		item.Name = "/"
	}
	return item, nil
}

func toItem(n memNode) vfs.VFSItem {
	return vfs.VFSItem{
		Name:      n.name,
		Size:      int64(len(n.data)),
		SizeKnown: true,
		IsDir:     n.isDir,
		MTime:     n.mtime,
		UnixMode:  0644,
	}
}

func (v *AIVFS) Join(elem ...string) string {
	joined := path.Join(elem...)
	if joined == "" {
		return "/"
	}
	return joined
}

func (v *AIVFS) Abs(p string) (string, error) { return v.normalize(p), nil }
func (v *AIVFS) Base(p string) string         { return path.Base(CleanPath(p)) }

func (v *AIVFS) Dir(p string) string {
	d := path.Dir(CleanPath(p))
	if d == "." {
		return "/"
	}
	return d
}

// writable marks the branches a human (or a copy operation) may change.
// Everything else is generated by the session and stays read only.
func writable(p string) bool {
	p = CleanPath(p)
	return p == draftFile ||
		p == ctxDir || strings.HasPrefix(p, ctxDir+"/") ||
		p == outDir || strings.HasPrefix(p, outDir+"/")
}

func (v *AIVFS) MkDir(ctx context.Context, p string) error {
	target := v.normalize(p)
	if !writable(target) {
		if strings.HasPrefix(target, chatDir) || target == "/" || !strings.Contains(strings.TrimPrefix(target, "/"), "/") {
			base := path.Base(target)
			if base != "." && base != ".." && base != "/" {
				target = path.Join(ctxDir, base)
			}
		}
	}
	if !writable(target) {
		return os.ErrPermission
	}
	return v.s.tree.mkdirAll(target)
}

func (v *AIVFS) Remove(ctx context.Context, p string) error {
	target := v.normalize(p)
	if !writable(target) || target == ctxDir || target == outDir {
		return os.ErrPermission
	}
	err := v.s.tree.remove(target)
	v.s.refresh()
	return err
}

func (v *AIVFS) Rename(ctx context.Context, oldPath, newPath string) error {
	from, to := v.normalize(oldPath), v.normalize(newPath)
	if !writable(from) || !writable(to) {
		return os.ErrPermission
	}
	return v.s.tree.rename(from, to)
}

func (v *AIVFS) SetAttributes(ctx context.Context, p string, item vfs.VFSItem) error { return nil }

func (v *AIVFS) GetCapabilities() vfs.VFSCapabilities {
	return vfs.VFSCapabilities{HasRandomAccess: true}
}

func (v *AIVFS) Search(ctx context.Context, p string, pattern string) (chan int64, error) {
	return nil, nil
}

// Open is what makes F5 out of the dialog work at all: f4 copies through
// Open plus ReadAt.
func (v *AIVFS) Open(ctx context.Context, p string) (vfs.ReadAtCloser, error) {
	v.s.refresh()
	target := v.normalize(p)
	data, ok := v.s.tree.readFile(target)
	if !ok {
		if altData, altOk := v.s.tree.readFile(path.Join(ctxDir, path.Base(target))); altOk {
			data, ok = altData, true
		} else if altData, altOk := v.s.tree.readFile(path.Join(outDir, path.Base(target))); altOk {
			data, ok = altData, true
		}
	}
	if !ok {
		return nil, os.ErrNotExist
	}
	return &memReader{data: data}, nil
}

func (v *AIVFS) Create(ctx context.Context, p string) (io.WriteCloser, error) {
	target := v.normalize(p)
	if !writable(target) {
		if strings.HasPrefix(target, chatDir) || target == "/" || !strings.Contains(strings.TrimPrefix(target, "/"), "/") {
			base := path.Base(target)
			if base != "." && base != ".." && base != "/" {
				target = path.Join(ctxDir, base)
			}
		}
	}
	if !writable(target) {
		return nil, os.ErrPermission
	}
	if n, ok := v.s.tree.stat(target); ok && n.isDir {
		return nil, os.ErrExist
	}
	return &memWriter{v: v, path: target}, nil
}

func (v *AIVFS) ParentVFS() vfs.VFS { return nil }

// Clone keeps the same dialog: a second panel on ai:// is the same
// conversation, not a copy of it.
func (v *AIVFS) Clone() vfs.VFS { return &AIVFS{s: v.s, cwd: v.cwd} }

// Close detaches this mount only. The dialog outlives the panel.
func (v *AIVFS) Close() error { return nil }

type memReader struct {
	data []byte
	off  int64
}

func (r *memReader) Size() int64 { return int64(len(r.data)) }

func (r *memReader) ReadAt(ctx context.Context, p []byte, off int64) (int, error) {
	if err := ctx.Err(); err != nil {
		return 0, err
	}
	if off >= int64(len(r.data)) {
		return 0, io.EOF
	}
	n := copy(p, r.data[off:])
	if n < len(p) {
		return n, io.EOF
	}
	return n, nil
}

func (r *memReader) Read(ctx context.Context, p []byte) (int, error) {
	n, err := r.ReadAt(ctx, p, r.off)
	r.off += int64(n)
	return n, err
}

func (r *memReader) Close() error { return nil }

// memWriter buffers the whole file and commits it on Close, so a cancelled
// copy leaves no half written entry in the dialog.
type memWriter struct {
	v      *AIVFS
	path   string
	buf    []byte
	failed error
}

func (w *memWriter) Write(p []byte) (int, error) {
	if w.failed != nil {
		return 0, w.failed
	}
	if len(w.buf)+len(p) > maxFileBytes {
		w.failed = errTooLarge
		return 0, w.failed
	}
	w.buf = append(w.buf, p...)
	return len(p), nil
}

func (w *memWriter) Close() error {
	if w.failed != nil {
		return w.failed
	}
	if err := w.v.s.tree.writeFile(w.path, w.buf); err != nil {
		return err
	}
	w.v.s.refresh()
	return nil
}

// refresh keeps session.md truthful after any change made through the panel.
func (s *Session) refresh() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.writeSessionFile()
}
