package action

import "strings"

// actionMenuOrder is the order every action-driven surface presents actions in:
// the generated menus, the keybar, the help topic list and the command palette
// all read it through GetOrderedActions. It is observable behaviour — editing
// this list rearranges the user's menu.
//
// The order is recorded here rather than emerging from registration because
// registration order is whatever Go's init() rules produce: file name order
// inside a package, import graph order across packages. Either would let a file
// move rearrange the menu with nothing to notice it.
//
// An action missing from this list is presented after every action that is in
// it, in registration order. That is the right default for a plugin, which
// cannot be listed here, and the wrong one for a new built-in action: add it at
// the position it belongs in and regenerate testdata/action_order.golden.
var actionMenuOrder = []string{
	"App.ScreenGrab",
	"App.CopyWindowTitle",
	"Macro.Reload",
	"App.ConfigEditor",
	"App.About",
	"App.CommandPalette",
	"App.Help",
	"App.MainMenu",
	"App.LastMenuItem",
	"Workspace.New",
	"Workspace.Fork",
	"Workspace.NewTerminal",
	"Workspace.Close",
	"Workspace.Next",
	"Workspace.Previous",
	"Workspace.List",
	"Debug.ScreenDump",
	"File.View",
	"File.ViewHex",
	"File.Edit",
	"File.New",
	"File.ApplyCommand",
	"File.Copy",
	"File.CopyInPlace",
	"File.Move",
	"File.CreateLink",
	"File.EditSymlink",
	"File.Rename",
	"File.MakeDir",
	"File.Delete",
	"File.DeletePermanent",
	"File.Attributes",
	"File.Share",
	"Panel.SystemExplorer",
	"Panel.SelectGroup",
	"Panel.DeselectGroup",
	"Panel.SelectCurrentExtension",
	"Panel.DeselectCurrentExtension",
	"Panel.InvertSelection",
	"Panel.RestoreSelection",
	"Panel.SelectNavigation",
	"Panel.ToggleCommandLineFocus",
	"Panel.UserMenu",
	"Panel.FileAssociations",
	"Panel.Base64EncodeFile",
	"Panel.Base64DecodeFile",
	"File.Find",
	"File.FindDuplicates",
	"Panel.CompareFolders",
	"Panel.SyncDirs",
	"File.RunRemoteCommand",
	"Panel.BackgroundJobs",
	"Panel.Bookmarks",
	"Panel.PluginMenu",
	"Panel.TempPanel",
	"Panel.CommandHistory",
	"Panel.FoldersHistory",
	"Panel.ViewerEditorHistory",
	"History.ImportFar2l",
	"History.ImportFar2lFolders",
	"Settings.ImportFar2l",
	"Panel.GoParent",
	"Panel.GoRoot",
	"Panel.HistoryBack",
	"Panel.HistoryForward",
	"Panel.ScrollNamesLeft",
	"Panel.ScrollNamesRight",
	"Panel.ScrollNamesHome",
	"Panel.ScrollNamesEnd",
	"Panel.CopyPath",
	"Panel.InsertPath",
	"Panel.CopyName",
	"Panel.CopySelectedNames",
	"Panel.CopySelectedPaths",
	"Panel.CopySelectedRealPaths",
	"Panel.SortUseGroups",
	"Panel.SortNumeric",
	"Panel.SortMenu",
	"Panel.GroupMenu",
	"Panel.GroupByNone",
	"Panel.GroupByName",
	"Panel.GroupByExtension",
	"Panel.GroupBySize",
	"Panel.GroupByPhysicalSize",
	"Panel.GroupByModified",
	"Panel.GroupByAccessed",
	"Panel.GroupByChanged",
	"Panel.GroupByOwner",
	"Panel.GroupByOwnerGroup",
	"Panel.GroupByPermissions",
	"Panel.GroupByAttributes",
	"Panel.GroupByModeText",
	"Panel.GroupByKind",
	"Panel.GroupByHidden",
	"Panel.GroupByExecutable",
	"Panel.GroupReverse",
	"Panel.GroupFoldersSeparately",
	"Panel.GroupSettings",

	"Settings.Language",
	"Settings.Panel",
	"Settings.PanelModes",
	"Settings.Editor",
	"Settings.Viewer",
	"Settings.Colorer",
	"Settings.Appearance",
	"Settings.Startup",
	"Settings.Portable",
	"Settings.Confirmations",
	"Settings.MouseWheel",
	"Settings.PathHints",
	"Settings.Hotkeys",
	"Settings.AutoUpdate",
	"Settings.CheckUpdates",
	"Settings.Proxy",
	"Settings.PluginConfiguration",
	"Settings.Plugins",
	"App.PlugRing",
	"App.SaveSettings",
	"App.ToggleWindowSize",
	"Panel.ToggleKeyBar",
	"Settings.MacKeyboard",
	"Panel.Rescan",
	"Panel.Swap",
	"Panel.Toggle",
	"Panel.ToggleLeftPanel",
	"Panel.ToggleRightPanel",
	"Panel.TogglePassivePanel",
	"Panel.InfoPanel",
	"Panel.QuickView",
	"Panel.Player",
	"Panel.SplitLeft",
	"Panel.SplitRight",
	"Panel.SplitUp",
	"Panel.SplitDown",
	"Panel.SplitActiveUp",
	"Panel.SplitActiveDown",
	"Panel.SplitReset",
	"Panel.SyncPanels",
	"Panel.ToggleInfoBytes",
	"Panel.ToggleHidden",
	"Panel.ViewBrief",
	"Panel.ViewMedium",
	"Panel.ViewDetailed",
	"Panel.ViewWide",
	"Panel.ViewMode5",
	"Panel.ViewMode6",
	"Panel.ViewMode7",
	"Panel.ViewMode8",
	"Panel.ViewMode9",
	"Panel.ViewMode0",
	"Panel.SortByName",
	"Panel.SortByExt",
	"Panel.SortByTime",
	"Panel.SortBySize",
	"Panel.SortUnsorted",
	"Panel.LeftDriveMenu",
	"Panel.RightDriveMenu",
	"Panel.EnterDirectory",
	"Panel.InsertFileName",
	"Panel.InsertLeftPath",
	"Panel.InsertRightPath",
	"App.Quit",
	"Debug.DummyOperation",
	"Terminal.ViewLog",
	"Terminal.EditLog",
	"Editor.Save",
	"Editor.SaveAs",
	"Editor.SwitchToViewer",
	"Editor.Quit",
	"Editor.Undo",
	"Editor.Redo",
	"Editor.Copy",
	"Editor.Cut",
	"Editor.Paste",
	"Editor.SelectAll",
	"Editor.DeleteLine",
	"Editor.DuplicateLine",
	"Editor.AddCursorAtNextOccurrence",
	"Editor.SkipOccurrence",
	"Editor.RemoveLastOccurrence",
	"Editor.SelectAllOccurrences",
	"Editor.MoveLineUp",
	"Editor.MoveLineDown",
	"Editor.Base64Menu",
	"Editor.Base64Encode",
	"Editor.Base64Decode",
	"Editor.CalculateExpression",
	"Editor.SortLines",
	"Editor.ToggleOvertype",
	"Editor.Search",
	"Editor.Replace",
	"Editor.SearchNext",
	"Editor.SearchForward",
	"Editor.SearchPrevious",
	"Editor.WordWrap",
	"Editor.HexMode",
	"Editor.DisasmMode",
	"Editor.ShowWhitespaces",
	"Editor.CodepageNext",
	"Editor.CodepageMenu",
	"Editor.ConvertCodepage",
	"Editor.InsertLeftPanelPath",
	"Editor.InsertRightPanelPath",
	"Editor.InsertActivePanelFileName",
	"Editor.DeleteSpacersForward",
	"Editor.ColorerMatchPair",
	"Editor.ColorerSelectPair",
	"Editor.ColorerSelectBlock",
	"Editor.ColorerListFunctions",
	"Editor.ColorerListErrors",
	"Editor.ColorerLocateFunction",
	"Editor.ColorerChooseType",
	"Editor.ColorerSelectRegion",
	"Editor.ColorerUpdateHighlighting",
	"Editor.ColorerReloadBase",
	"Viewer.SwitchToEditor",
	"Viewer.Reload",
	"Viewer.ToggleHighlighting",
	"Viewer.Quit",
	"Viewer.WrapMode",
	"Viewer.HexMode",
	"Viewer.DisasmMode",
	"Viewer.Search",
	"Viewer.SearchNext",
	"Viewer.SearchPrevious",
	"Viewer.CodepageNext",
	"Viewer.CodepageMenu",
	"Editor.Settings",
	"Viewer.Settings",
	"Panel.Mount",
	"Panel.MountRW",
	"Panel.MountList",
	"App.Spreadsheet",
	"App.SQLite",
	"Panel.Left.ViewBrief",
	"Panel.Left.ViewMedium",
	"Panel.Left.ViewDetailed",
	"Panel.Left.ViewWide",
	"Panel.Left.SortByName",
	"Panel.Left.SortByExt",
	"Panel.Left.SortByTime",
	"Panel.Left.SortBySize",
	"Panel.Left.SortUnsorted",
	"Panel.Left.SortUseGroups",
	"Panel.Left.SortNumeric",
	"Panel.Left.GroupMenu",
	"AI.Left.ViewContext",
	"AI.Left.ViewChat",
	"AI.Left.ViewOut",
	"AI.Left.ViewMem",
	"Panel.Right.ViewBrief",
	"Panel.Right.ViewMedium",
	"Panel.Right.ViewDetailed",
	"Panel.Right.ViewWide",
	"Panel.Right.SortByName",
	"Panel.Right.SortByExt",
	"Panel.Right.SortByTime",
	"Panel.Right.SortBySize",
	"Panel.Right.SortUnsorted",
	"Panel.Right.SortUseGroups",
	"Panel.Right.SortNumeric",
	"Panel.Right.GroupMenu",
	"AI.Right.ViewContext",
	"AI.Right.ViewChat",
	"AI.Right.ViewOut",
	"AI.Right.ViewMem",
	"Viewer.GoTo",
	"Editor.GoTo",
	"App.Background",
	"App.Arkanoid",
	"AI.TogglePanel",
	"AI.Ask",
	"AI.NewSession",
	"AI.ApplyPatch",
	"AI.Setup",
	"AI.Help",
	"AI.AttachAPSpec",
	"AI.ListModels",
}

// actionMenuPosition indexes actionMenuOrder by registry key.
var actionMenuPosition = func() map[string]int {
	positions := make(map[string]int, len(actionMenuOrder))
	for position, name := range actionMenuOrder {
		positions[strings.ToLower(name)] = position
	}
	return positions
}()

// actionMenuRank answers where a registry key sits in the presentation order.
// Keys the table does not know share one rank, so a stable sort leaves them in
// registration order behind the ones it does.
func actionMenuRank(key string) int {
	if position, ok := actionMenuPosition[key]; ok {
		return position
	}
	return len(actionMenuOrder)
}
